### ISSUE TITLE
Unable to use Limit and Skip

### ISSUE THREAD

**Issue by PBhadoo** [mongodb-developer/cloudflare-worker-rest-api-realm-atlas#11]
`const cursor = collection.find(query);` works

while

`const cursor = collection.find(query).limit(10);`

or using `skip(100)` doesn't works

says not a valid function.

**Comment by MaBeuLux88** [comment]
Hi @PBhadoo,

Thanks for reaching out.

https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.MongoDBCollection.html#find

Wrong signature. It's not the find from the Node.js driver. 

More details here: https://www.mongodb.com/docs/realm/web/mongodb/ 

Also I'd recommend using the Atlas Data API instead of this hack with the Realm web SDK (supposed to be used in a front-end) now that it's released.

Cheers,
Maxime.

**Comment by PBhadoo** [comment]
> Hi @PBhadoo,
> 
> Thanks for reaching out.
> 
> https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.MongoDBCollection.html#find
> 
> Wrong signature. It's not the find from the Node.js driver.
> 
> More details here: https://www.mongodb.com/docs/realm/web/mongodb/
> 
> Also I'd recommend using the Atlas Data API instead of this hack with the Realm web SDK (supposed to be used in a front-end) now that it's released.
> 
> Cheers, Maxime.

The Limit got working.

but skip isn't there and still not working. Any possible way?

I'll also try Atlas Data API but this script works in Cloudflare Workers and easiest for me to deploy without maintenance.

**Comment by MaBeuLux88** [comment]
`skip()` is currently not supported due to how Atlas App Services works (related to security rules).

Even if you could use it, it wouldn't be optimized. `skip()` is optimized when executed on the core database by not fetching the docs. But here it can't work like that in App services. 

The alternative is to use find with range queries and indexes. This solution requires a bit more work but it's optimal. 
https://www.mongodb.com/docs/manual/reference/method/cursor.skip/#using-range-queries

**Comment by MaBeuLux88** [comment]
Note that the Atlas Data API is a better tool to do this job now. 

https://www.mongodb.com/docs/atlas/api/data-api/

And skip is available there: https://www.mongodb.com/docs/atlas/api/data-api-resources/#request-body-1

Edit: This is false. Read below.

> The Realm Web SDK creates an entire connection pool for each call of the cloudflare worker (because there is no caching of the MongoDB connection). The Data API removes this problem. It was released shortly after this blog post. I should make a new one.

**Comment by MaBeuLux88** [comment]
Update because the guy in the previous post - just above this one - clearly doesn't know what he is talking about! :rofl: 

The connection pool is actually managed by the Atlas application in the Atlas App Service and it's constantly connected to the cluster in Atlas. So each time you spawn a new Cloudflare worker, you actually need to go through the authentication & authorization processes before being able to run a MongoDB query. In this blog post it's done via API keys. 

Check out my new note in the introduction of the [blog post](https://www.mongodb.com/developer/products/atlas/cloudflare-worker-rest-api/) for more details.
