### ISSUE TITLE
DB Connection

### ISSUE THREAD

**Issue by kakopappa** [mongodb-developer/cloudflare-worker-rest-api-realm-atlas#13]
Just wondering whether it's making a database connection with the every request or does it keep the connection open ?

**Comment by MaBeuLux88** [comment]
That's the main reason why this blog post should be deprecated... 
From my understanding, it's creating a new connection every time the worker executes the code because there is no cache to actually remember any context from the previous execution.

I should write a new blog post because since this blog post was written, MongoDB released the Atlas Data API which is a better way to talk to MongoDB when using the Driver isn't an option. Which is basically the problem we are trying to work around here.

So yeah. My advice is don't do that in production. It was more a proof of concept than a production ready piece of code.
Use the Atlas Data API instead. This will resolve the connection problem issue.

**Comment by MaBeuLux88** [comment]
That's the main reason why this blog post should be deprecated... 
From my understanding, it's creating a new connection every time the worker executes the code because there is no cache to actually remember any context from the previous execution.

I should write a new blog post because since this blog post was written, MongoDB released the Atlas Data API which is a better way to talk to MongoDB when using the Driver isn't an option. Which is basically the problem we are trying to work around here.

So yeah. My advice is don't do that in production. It was more a proof of concept than a production ready piece of code.
Use the Atlas Data API instead. This will resolve the connection problem issue.

**Comment by kakopappa** [comment]
Thanks for your input. 

i noticed, in AWS, if you don’t terminate them and leave them hanging you can set to callbackWaitsForEmtpyEventLoop = false however this feature is not in cloudflare workers


context.callbackWaitsForEmtpyEventLoop = false

**Comment by MaBeuLux88** [comment]
In AWS you can have a shared context and reuse the same connection for each lambda execution.
https://www.mongodb.com/docs/atlas/manage-connections-aws-lambda/
