### ISSUE TITLE
Realm App.login: Request Failed: (status 525)

### ISSUE THREAD

**Issue by Natas0007** [mongodb-developer/cloudflare-worker-rest-api-realm-atlas#6]
Hey there...great detailed tutorial at [https://www.mongodb.com/developer/how-to/cloudflare-worker-rest-api-realm/](url)!  However, after following the tutorial precisely, I'm receiving the below error on `var user = await App.logIn(credentials);`.  The app name in this error is application-0-2983:

Error: Request failed (GET https://stitch.mongodb.com/api/client/v2.0/app/application-0-2983/location): (status 525)

I can even do a GET directly against [https://stitch.mongodb.com/api/client/v2.0/app/application-0-2983/location](url) without issue. It returns:

`{
"deployment_model": "LOCAL",
"location": "US-VA",
"hostname": "https://us-east-1.aws.stitch.mongodb.com",
"ws_hostname": "wss://ws.us-east-1.aws.realm.mongodb.com"
}`

To make sure I wasn't doing something incorrectly in my Realm config, I followed MongoDB's own tutorial here to setup a new Realm: [https://docs.mongodb.com/realm/tutorial/realm-app/](url).  I am receiving the exact same error against this Realm also (fyi, it uses email/pass credentials instead of apiKey).

For what it's worth, I currently have my Atlas cluster behind these Realms open to any source (0.0.0.0/0) for testing.

I'm unable to find any info on this error to get it resolved.  Did something maybe change recently in how this authentication needs to be configured?  Any assistance would be much appreciated!  Thank you!

**Comment by tomduncalf** [comment]
Hi @Natas0007, sorry to hear you're having issues!

I tried to reproduce your issue, but it seemed to work OK for me.

I'm not familiar with Cloudflare Workers, but from searching for this error code, it sounds like it could be related to the SSL settings for the domain the worker is deployed to (e.g. https://community.cloudflare.com/t/fetch-from-aws-api-gateway-fails-from-worker-with-error-525-revealing-the-origin-url-in-error-page/51320 and  https://community.cloudflare.com/t/error-origin-ssl-handshake-error-525/294302/13).

The solution they suggest is to change your SSL settings for the domain in the Cloudflare Dashboard to "Full" rather than "Full (Strict)" – would you be able to check this?

![image](https://user-images.githubusercontent.com/5458070/154726777-448bc871-6fc4-4939-9837-650d0339fabf.png)

I tried setting mine to "Full (Strict)" and did not hit the same issue as you, but maybe there are other factors at play. Let us know how it goes!

**Comment by Natas0007** [comment]
Thanks for the detailed response @tomduncalf!  I will give the SSL settings a try soon.  To get the api up in the meantime, I have it running as an Azure App Service instead of a Cloudflare Worker.  Thanks again!

**Comment by tomduncalf** [comment]
No worries, glad you managed to find a workaround!
